# Generated by Django 2.2.1 on 2019-06-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mobile_category_id',
            field=models.IntegerField(default=0),
        ),
    ]
