# Generated by Django 2.2.1 on 2019-08-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_itemsinshared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fromwebprodfields',
            name='measure',
            field=models.CharField(blank=True, max_length=4, verbose_name='измерение'),
        ),
        migrations.AlterField(
            model_name='fromwebprodfields',
            name='volume',
            field=models.CharField(blank=True, max_length=10, verbose_name='объем упаковки'),
        ),
    ]
